language: c
compiler: gcc
sudo: required
dist: trusty
cache:
  - apt
before_install:
  - sudo add-apt-repository ppa:vala-team -y
  - sudo add-apt-repository ppa:gnome3-team/gnome3-staging
  - sudo apt-get -qq update
  - sudo apt-get install -y cmake valac libgtk-3-dev libgtop2-dev libgee-0.8-dev 
script:
  - mkdir build
  - cd build
  - cmake ..
  - sudo make install